name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          # echo ${{ secrets.SECRET_TOKEN }}
          # echo "Trick to echo GitHub Actions Secret:  "
          # echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 

      # Use a GitHub Actions secret variable in a bash shell
      # - name: Step 2 - GitHub Action if statement (true)
      #   env: 
      #     WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      #   if:  env.WHO_TO_TRUST == 'TrustNo1'
      #   run: echo "I know what the secret token is!"

      # # A GitHub Actions if statement with a secret environment variable
      # - name: Step 3 - Conditional GitHub Action (false)
      #   shell: bash
      #   env: 
      #     WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      #   if:  env.WHO_TO_TRUST != 'TrustNobody'
      #   run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"


